spring:
  application:
    name: vigacat
  profiles:
    active: local

server:
  port: 8081
  servlet.contextPath: /vigacat-security

logging:
  level:
    root: info

security:
  url: http://localhost:8081

app:
  name: Security